import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import PageNavbar from './components/PageNavbar';
import Head from 'next/head';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'CompSci and Coding Club',
  description: 'Generated by create next app',
  icons: '/media/codingClub-diamond-logo.jpg',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <Head>
        <link rel='icon' href='./media/codingClub-diamond-logo.jpg' />
      </Head>
      <body className={inter.className}>
        <PageNavbar />
        {children}
      </body>
    </html>
  );
}
